[browser]
title = "Signal Analysis Browser"

[[workspaces]]
use = "examples.profile:create_generic_workspace"
path = "./examples"
id = "generic-example"
name = "Generic Example Workspace"

[[workspaces]]
use = "examples.profile:create_sigmf_workspace"
path = "./examples"
id = "sigmf-viewer"
name = "Recorded signals"

[workspaces.config]
data_root = "./examples/data"

[[workspaces]]
use = "examples.profile:create_sigmf_matplotlib_workspace"
path = "./examples"
id = "sigmf-matplotlib-viewer"
name = "Recorded signals (Matplotlib)"

[workspaces.config]
data_root = "./examples/data"

[[workspaces]]
use = "examples.profile:create_lfm_collection_workspace"
path = "./examples"
id = "lfm-collection"
name = "10 MHz LFM Collection"

[workspaces.config]
data_root = "./data/lfm-collection"

[[workspaces]]
use = "examples.profile:create_lfm_full_recording_workspace"
path = "./examples"
id = "lfm-full-recording"
name = "10 MHz LFM Collection (Whole Recording)"

[workspaces.config]
data_root = "./data/lfm-collection"

[[workspaces]]
use = "examples.profile:create_pri_workspace"
path = "./examples"
id = "pri-waterfall"
name = "PRI analysis"

[workspaces.config]
data_root = "./examples/data"
