"""Stable public API for typed, data-driven workspace plugins."""

from sigvue.core.plugin import (
    Analysis,
    Delivery,
    DeliveryContext,
    DiscoveryColumn,
    DataResource,
    DirectorySource,
    ParameterContext,
    Presentation,
    Source,
    TraceStyle,
    ViewContext,
    Workspace,
)
from sigvue.core.page import AxisNavigation, PlaybackMode, Segment, TimeUnit
from sigvue.core.capabilities import (
    Annotation,
    AnnotationField,
    AnnotationPlotBinding,
    AnnotationRequest,
    Batch,
    BatchDestination,
    BatchRequest,
    BatchResult,
    CapabilityChoice,
    Annotator,
    Exporter,
    ExportRequest,
)

__all__ = [
    "Analysis",
    "AxisNavigation",
    "Annotation",
    "AnnotationField",
    "AnnotationPlotBinding",
    "AnnotationRequest",
    "CapabilityChoice",
    "Batch",
    "BatchDestination",
    "BatchRequest",
    "BatchResult",
    "Delivery",
    "DeliveryContext",
    "DiscoveryColumn",
    "Annotator",
    "Exporter",
    "DataResource",
    "DirectorySource",
    "ExportRequest",
    "PlaybackMode",
    "ParameterContext",
    "Presentation",
    "Segment",
    "Source",
    "TraceStyle",
    "ViewContext",
    "Workspace",
    "TimeUnit",
]
